version: '3.8'
services:
  timescaledb:
    build: 
      context: ./
    container_name: timescaledb_custom
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ts_user        
      POSTGRES_PASSWORD: ts_password  
      POSTGRES_DB: ts_data_db
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ts_user -d ts_data_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

volumes:
  timescaledb_data: